name: YouYinan
description: Blogging about stuffs
meta_description: "我的iOS开发之旅"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://yyn835314557.github.io/'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
# url:            '/rss.xml'
url:            'blog url'
author:         'YouYinan'
